### ISSUE TITLE
3 days max shown in the reward gui

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [SkyFire55/daily-rewards#1]
so i made 7 day rewards but for some reason even if i restart/reload the plugin it keeps saying that there are only 3 days with rewards

`{

  debug=false //some debug stuffs, don't touch without need

  hardMode=true //push player back to the first day if he missed one day or not

  daycap=7 //after this day player will be pushed back to the first day anyway - end of his row

  days{

    1: { //day number - if you will create 1,2 and 4 days, player shall not take reward for 3 day, but he will on 4 day

      icon: { // your icon settings for this day - player will see it in GUI

        item: "pixelmon:poke_ball" // materialname for item - fill free to use metadata

        name: "Day 1"

        lore: {

          1: "Reward Day 1"

          2: "Reward: 12 poke ball"

        }

      }

      rewards: [ //rewards, which player will take in this day

        {reward: "ITEM pixelmon:poke_ball 12"}, //ITEM <materialname:meta> <amount> - just give items to player

      ]

    }

    2: {

      icon: {

        item: "minecraft:diamond"

        name: "Day 2"

        lore: {

          1: "Reward Day 2"

          2: "Reward: 1000$"

        }

      }

      rewards: [

        {reward: "MONEY 1000"}, //give money to player

      ]

    }

    3: {

      icon: {

        item: "pixelmon:rare_candy"

        name: "Day 3"

        lore: {

          1: "Reward Day 3"

          2: "Reward: 3 Rare Candy"

        }

      }

      rewards: [

        {reward: "ITEM pixelmon:rare_candy 3"}, //command, which will execute from console when player take this reward

      ] //use <player> placeholder - it's player's name who takes the reward

    }

	 4: {

      icon: {

        item: "pixelmon:master_ball"

        name: "Day 4"

        lore: {

          1: "Reward Day 4"

          2: "Reward: 1 Master Ball"

        }

      }

      rewards: [

        {reward: "ITEM pixelmon:master_ball 1"}, //command, which will execute from console when player take this reward

      ] //use <player> placeholder - it's player's name who takes the reward

    }
	
	 5: {

      icon: {

        item: "pixelmon:super_potion"

        name: "Day 5"

        lore: {

          1: "Reward Day 5"

          2: "Reward: 10 Super Potion"

        }

      }

      rewards: [

        {reward: "ITEM pixelmon:super_potion 10"}, //command, which will execute from console when player take this reward

      ] //use <player> placeholder - it's player's name who takes the reward

    }
	
	6: {

      icon: {

        item: "pixelmon:pumpkin_berry"

        name: "Day 6"

        lore: {

          1: "Reward Day 6"

          2: "Reward: 20 Pumpkin Berry"

        }

      }

      rewards: [

        {reward: "ITEM pixelmon:pumpkin_berry 20"}, //command, which will execute from console when player take this reward

      ] //use <player> placeholder - it's player's name who takes the reward

    }
	
		7: {

      icon: {

        item: "pixelmon:gift_box"

        name: "Day 7"

        lore: {

          1: "Reward Day 7"

          2: "Reward: Mistery Gift"

        }

      }

      rewards: [

        {reward: "ITEM pixelmon:master_ball 3"}, //command, which will execute from console when player take this reward

      ] //use <player> placeholder - it's player's name who takes the reward

    }
  }

}`

**Comment by VimbaTheFish** [comment]
API version(Minecraft version)? Any errors in console? Does GUI shows your first 3 rewards or rewards from standart config?
Oh, and does command /dr take works with all of your rewards?

**Comment by VimbaTheFish** [comment]
I don't know, where is error here, but when I downloaded this config and tried, it didn't worked. Try this one - replace materialnames with yours.

https://pastebin.com/kmqq7ZQV
