### ISSUE TITLE
Changing PC time makes it easy to get rewards

### ISSUE THREAD

**Issue by Lorrainrm** [SkyFire55/daily-rewards#10]
I didn't tested it, but apparantly some got it working that way:

Ppl reconnects internet and change pc time to get all the rewards.

**Comment by VimbaTheFish** [comment]
THat's possible to take not more than 2 rewards in a day. And those 2 rewards are possible to take only after moment day "refreshes" and starts a new one. Plugin checks only server time. Please, check this and say, how to reproduce this bug, if I'm wrong.
