### ISSUE TITLE
Error after /dr clear  then try to reredeem!

### ISSUE THREAD

**Issue by BunnyF00F00** [SkyFire55/daily-rewards#12]
Ill go step by step
I enter server,
DR pops up nice freebies, I take
But I want more type /dr clear
response from server : every player can now take a reward again! Time set to current!
greedy me types /dr show  gui pops up I click on day 1 and "press here to take you're reward".........
Server response with : Eco doesn't work Something went wrong. Cannot give reward to player - maybe inventory full!

As you can see inventory is not full.

Unless it is just me, as I am new to all this.

![desktop screenshot 2018 09 17 - 18 18 54 51](https://user-images.githubusercontent.com/43357059/45653632-b4798380-baa6-11e8-95c8-8d79c0312444.png)

**Comment by VimbaTheFish** [comment]
Do you have economy plugin installed on your server?

And secondly, do u know that you should user /dr clear only one time - to set time of moving to the next day?

**Comment by BunnyF00F00** [comment]
no economy plugin just huskycrates. 
"/dr clear - move server to the next day and set new time starting point. All players can take rewards again."
If above clears the day it should in turn reset the day and start over again. If i have 100 players on the server that is alot of /user commands.
nless this is not the way you have programed it. 
I see what you mean, that being said why did it corrupt the config?

**Comment by VimbaTheFish** [comment]
Players can take rewards every 24 hour FROM THE TIME MOMENT when u used /dr clear. You don't need to do it every day. This command is for setting, in what moment of the day it should push players to the next day and should be used only one time.

And yep, economy plugin is required.
