### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by unovalegends** [SkyFire55/daily-rewards#2]
I started it  up and try to make any commands and all it does it error

https://hastebin.com/yabosigebe.vbs

**Comment by VimbaTheFish** [comment]
What minecraft version is it?
Try to use latest Spongeforge(or Spongevanilla) build.

**Comment by unovalegends** [comment]
1.10.2

**Comment by VimbaTheFish** [comment]
If sponge version updating doesn't help, show me your config file, please. If you cannot load plugin even in first time and even after sponge version update, tell me here, i'll make special 1.10 and 1.11 builds.

**Comment by VimbaTheFish** [comment]
Try to download api5-6 version. If it help, close this issue, please. If not - send error here.

**Comment by unovalegends** [comment]
Okay I got another error report maybe you can tell me 
https://hastebin.com/wahaxucile.sql

Here my config 
https://hastebin.com/abewarejan.coffeescript

**Comment by VimbaTheFish** [comment]
Look string №70 - you missed one ". So, plugin cannot read your config. 
If you will have errors like this again - just look the first string of your log. It shows you string number, which plugin cannot parse, for example, here you can see Reader: 70

**Comment by unovalegends** [comment]
Still not working 
Error
https://hastebin.com/ebitipepib.md

update config
https://hastebin.com/girahedohe.sm

**Comment by VimbaTheFish** [comment]
147 - ITEM reward doesn't have amount.
Next time turn on days one by one to find mistake in a config.

**Comment by unovalegends** [comment]
IT works but it does spam on console 
09.01 23:42:00 [Server] Server thread/ERROR [dailyrewards]: There is no such a player: 02eef0da-b2ec-4556-b511-9307ae2cdae5

Also when the server restart does it effect everyone days?  If they miss a day do they get started back to day 1 (I hope) or it doesn't  effect there days?

**Comment by VimbaTheFish** [comment]
It's only time-depended system. If you generated your time config file or used command /dr clear at 2:00, so every day after 2:00 players can take new rewards.
If you have hard-mode turned off, players will not lose all their days if they missed one. If you will turn it on - they will. It's turned off by default.

It spams only when player log in for the first time. But yep, I agree, that's annoying a little. I'll fix it in next versions.

**Comment by unovalegends** [comment]
I didn't do /dr clear as in I just did /dr reload to get the new config which everyone claim right after day one. So if I leave it like that it will run the day around the same time I reload right?

**Comment by VimbaTheFish** [comment]
/dr reload and /dr clear are different commands. You can use reload anytime without any problems, change what you need and when you need. Clear moves ALL players to the next day, just like day is over and started new one. They can lose their days if you turned on hardmod. This command sets new startpoint timer - from this moment every 24 hours new day starts.
So, if u use /dr clear in 22:38, all players will move to the next day, and since this moment every day in 22:38 plugin will start new day. That means players can take new reward every day after 22:38.

**Comment by unovalegends** [comment]
Do I have to do /dr clear or can I just leave it alone?

**Comment by VimbaTheFish** [comment]
You have to use it only one time - just to set time when you want to set the startpoint. By default startpoint time will be the same with time you started your plugin first time.
Players anyway can take reward only one time in 24 hours, question is only - when the next day starts. So, you can mark, when new day starts with /dr clear command. If yu don't care when it starts - leave this option alone and don't worry about it.
If you want to set the startpoint at 00:00, just use /dr clear at 00:00. Players will take new rewards only after 00:00.

**Comment by unovalegends** [comment]
Thank you so much! Love how quick you respond and I'm so excited for this plugin :)
