### ISSUE TITLE
Error with daycap more then 7 and an idea

### ISSUE THREAD

**Issue by Krosta8** [SkyFire55/daily-rewards#3]
Hello,
I wanted to have daycap 21 (maybe more) and if I change it from 7 to 14 or 21, the reward GUI looks like the same (still for daycap 7). When I tried to add reward for day 14, I got an error on join and on /dr show
Error: https://hastebin.com/vitigileda.vbs
Using SpongeForge 1.12.2 Build 2825 (API 7.1.0) and DailyRewards 1.1.3

And I have an idea for your plugin.
Could you add something like lottery? 
I mean like this:
I can set three commands/items/money amount and it will randomly choose from this three options (best to be able to set for each chance in %)
Example: 
      rewards: [
        {lottery 50: "CMD give <player> diamond 1"}
        {lottery 30: "CMD give <player> diamond 2"}
        {lottery 20: "CMD give <player> diamond 5"}
      ]
Where the number represent the chance to get this option.

Another idea, which I have.
When a player received his reward, it says "Here is your reward."
Could you add an option to set for each reward different message on receiving the reward?

**Comment by VimbaTheFish** [comment]
Can you show me your config file? I want to be sure that there is no mistake there.
About ideas - yep, I think it's possible to make something like this. I'll do it in next versions.

**Comment by Krosta8** [comment]
I just take your default config file and change daycap value and copy day 3, rename it to day 14 and that's all.
https://hastebin.com/ofibeyukum.scala

**Comment by VimbaTheFish** [comment]
Fixed in 1.2.0
