### ISSUE TITLE
Title & Lore

### ISSUE THREAD

**Issue by MageFX** [SkyFire55/daily-rewards#4]
Does not support color codes & 

Can this be added please.

**Comment by MageFX** [comment]
http://prntscr.com/hxlvx5

Lore all messed up also.

**Comment by VimbaTheFish** [comment]
It needs §(alt+21), not &. But yep, you are right, I'll add & support in next versions.

**Comment by MageFX** [comment]
I've preconfigured it but I'll hold off using till added. Thanks for
replying.

**Comment by VimbaTheFish** [comment]
Fixed in version 1.2.0
