### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by Krosta8** [SkyFire55/daily-rewards#7]
Hello,
I found a problem with plugin version 1.2.1 for API5-6.
Here is the error on server start-up https://hastebin.com/bixevetexu.swift
Using SpongeForge 1.10.2 API 5.2.0, latest build
Here is my config https://hastebin.com/enebuzegej.scala

Do you have any idea, why am I getting this error?

**Comment by VimbaTheFish** [comment]
Sure - 206 string - If you want to set one item you should type 1. For example, "ITEM minecraft:diamond 1".

**Comment by Krosta8** [comment]
Thank you a lot! :relaxed:
