### ISSUE TITLE
Small sugestion - cd to open the daily gui

### ISSUE THREAD

**Issue by Lorrainrm** [SkyFire55/daily-rewards#9]
Ello!
I got a server with flexible login (adds /register and /login) and it blocks any interact or even the gui opening for the daily reward.

Do you think you cold add perhaps a config where we could add a delay before opening the automatic daily reward gui or it only opens after the player login?

Peace

**Comment by VimbaTheFish** [comment]
Ye, that's possible! I'll make it when I have a time

**Comment by VimbaTheFish** [comment]
Done! Check releases (v.1.3.1)
https://github.com/SkyFire55/daily-rewards/releases

**Comment by Lorrainrm** [comment]
Lovely! Thank you!

**Comment by VimbaTheFish** [comment]
Ye
Sorry for DELAY (Badum-tss)
